### ISSUE TITLE
failing TestFileFilter test on Windows

### ISSUE THREAD

**Issue by marten-seemann** [ipfs/go-ipfs-files#37]
```
--- FAIL: TestFileFilter (0.00s)
  panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  	panic: runtime error: invalid memory address or nil pointer dereference
  [signal 0xc0000005 code=0x0 addr=0x40 pc=0xaefc19]
  
  goroutine 23 [running]:
  testing.tRunner.func1.1(0xb2d520, 0xdac870)
  	C:/hostedtoolcache/windows/go/1.15.12/x64/src/testing/testing.go:1072 +0x310
  testing.tRunner.func1(0xc0000c0a80)
  	C:/hostedtoolcache/windows/go/1.15.12/x64/src/testing/testing.go:1075 +0x43a
  panic(0xb2d520, 0xdac870)
  	C:/hostedtoolcache/windows/go/1.15.12/x64/src/runtime/panic.go:969 +0x1c7
  github.com/ipfs/go-ipfs-files.(*mockFileInfo).Sys(0xc00008ae80, 0xb87f9c, 0x5)
  	<autogenerated>:1 +0x39
  github.com/ipfs/go-ipfs-files.isHidden(0xbf8d60, 0xc00008ae80, 0x5)
  	D:/a/go-ipfs-files/go-ipfs-files/is_hidden_windows.go:22 +0xb3
  github.com/ipfs/go-ipfs-files.(*Filter).ShouldExclude(0xc000085140, 0xbf8d60, 0xc00008ae80, 0x0)
  	D:/a/go-ipfs-files/go-ipfs-files/filter.go:45 +0x10b
  github.com/ipfs/go-ipfs-files.TestFileFilter(0xc0000c0a80)
  	D:/a/go-ipfs-files/go-ipfs-files/filter_test.go:47 +0x2f3
  testing.tRunner(0xc0000c0a80, 0xba4000)
  	C:/hostedtoolcache/windows/go/1.15.12/x64/src/testing/testing.go:1123 +0xef
  created by testing.(*T).Run
  	C:/hostedtoolcache/windows/go/1.15.12/x64/src/testing/testing.go:1168 +0x2b3
  FAIL	github.com/ipfs/go-ipfs-files	0.045s
  FAIL

**Comment by masih** [comment]
Fixed by https://github.com/ipfs/go-ipfs-files/pull/39
